### ISSUE TITLE
Don't hide exception cause: The requested resource is not available

### ISSUE THREAD

**Issue by etagwerker** [jin/hnrb#1]
Hello, 

I just ran into an issue while using the gem. I kept getting `"The requested resource is not available"` which was hiding the real reason why the `get_item` call wasn't working. 

I think that you should let `send_get_request_to` raise whatever it finds. In my case it was raising this: 

```
*** OpenSSL::SSL::SSLError Exception: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

It'll make it easier to fix your code if you don't "hide" the original exception with the RuntimeError.

**Comment by jin** [comment]
Thanks for this! I've stopped working on this a long time ago - glad to see someone actually using it.
